<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '(new)' => '(nuevo)',
    'Active' => 'Activo',
    'Add new' => 'Agregar nuevo',
    'Add new root' => 'Agregar nueva raíz',
    'Admin Settings' => 'Opciones de Administrador',
    'Already at bottom-most node in the hierarchy.' => 'Ya está en la opción más baja en la jerarquía',
    'Already at left-most node in the hierarchy.' => 'Ya está en la opción más a la izquierda en la jerarquía.',
    'Already at right-most node in the hierarchy.' => 'Ya está en la opción más a la derecha de la jerarquía.',
    'Already at top-most node in the hierarchy.' => 'Ya está en la opción más alta de la jerarquía.',
    'Are you sure you want to remove this node?' => '¿Está seguro que quiere remover este nodo?',
    'Cannot create node. Parent node is not saved or is invalid.' => 'No se puede crear el nodo. El nodo padre no está guardado o es inválido.',
    'Cannot move this node as the node details are not saved yet.' => 'No se puede mover este nodo ya que los detalles del mismo no esta guardados aún.',
    'Clear search results' => 'Limpiar resultados de búsqueda',
    'Collapsed' => 'Contraido',
    'Default' => 'Por defecto',
    'Delete' => 'Borrar',
    'Depth' => 'Profundidad',
    'Disabled' => 'Deshabilitado',
    'Error removing the node. Please try again later.' => 'Error al remover el nodo. Por favor intente más tarde.',
    'Error while creating the node. Please try again later.' => 'Ocurrió un error mientras se creaba el nodo. Por favor intente más tarde.',
    'Error while moving the node. Please try again later.' => 'Ocurrió un error mientras se movia el nodo. Por favor intente más tarde.',
    'Error while removing the node. Please try again later.' => 'Ocurrió un error mientras se borraba el nodo. Por favor intente más tarde.',
    'Error while saving the node. Please try again later.' => 'Ocurrió un error mientras se guardaba el nodo. Por favor intente más tarde.',
    'Error while viewing the node. Please try again later.' => 'Ocurrió un error mientras se leía el nodo. Por favor intente más tarde.',
    'ID' => 'ID',
    'Icon' => 'Ícono',
    'Icon Type' => 'Tipo de Ícono',
    'Left' => 'Izquierda',
    'Movable Down' => 'Movible hacía Abajo',
    'Movable Left' => 'Movible hacía la Izquierda',
    'Movable Right' => 'Movible hacía la Derecha',
    'Movable Up' => 'Movible hacía Abajo',
    'Move Down' => 'Bajar',
    'Move Left' => 'A la Izquierda',
    'Move Right' => 'A la Derecha',
    'Move Up' => 'Subir',
    'Name' => 'Nombre',
    'No valid tree nodes are available for display. Use toolbar buttons to add tree nodes.' => 'No hay nodos del árbol válidos para mostrar. Use la barra de herramientas para agregar nodos.',
    'Node # {id} - \'{name}\': {error}' => 'Nodo # {id} - \'{name}\': {error}',
    'Read Only' => 'Sólo lectura',
    'Refresh' => 'Actualizar',
    'Removable' => 'Removible',
    'Removable (with children)' => 'Removible (con sus hijos)',
    'Reset' => 'Reiniciar',
    'Right' => 'Derecha',
    'Root' => 'Raíz',
    'Save' => 'Guardar',
    'Saved the node details successfully.' => 'Se han guardado los detalles del nodo con éxito',
    'Search...' => 'Buscar...',
    'Select a node by clicking on one of the tree items.' => 'Seleccione un nodo al hacer click en uno de los items del árbol',
    'Select...' => 'Seleccione...',
    'Selected' => 'Seleccionado',
    'The node was moved successfully.' => 'El nodo fue movido con éxito.',
    'The node was removed successfully.' => 'El nodo fue removido con éxito',
    'The node was successfully created.' => 'El nodo fue creado con éxito',
    'The selected node cannot be moved.' => 'El nodo seleccionado no pudo ser movido.',
    'The untitled node was removed.' => 'El nodo sin título fue removido.',
    'This operation is not allowed.' => 'Esta operación no está permitida.',
    'Untitled' => 'Sin título',
    'Visible' => 'Visible',
];
